<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Configuration</name>
   <tag></tag>
   <elementGuidId>1cc6f222-141b-49c2-8791-2fb93f9e3fe6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Configuration')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>369f2aae-19d5-406a-a2d2-cd40bcf1811b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-gray-700 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium</value>
      <webElementGuid>1c1184d2-3370-49d5-af3f-2490879743d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>page/configurations/</value>
      <webElementGuid>f2e3aaa6-8c98-489e-87bb-52fedfffe9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Configuration</value>
      <webElementGuid>57a5fe98-55c9-406d-8f5b-f2ebfa445541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;h-full bg-gray-100&quot;]/body[@class=&quot;__className_0ec1f4 bg-white mx-auto h-full&quot;]/header[1]/nav[@class=&quot;bg-white border-2 border-white border-b-gray-100&quot;]/div[@class=&quot;mx-auto- -max-w-7xl px-4 sm:px-6 lg:px-8&quot;]/div[@class=&quot;flex h-16 items-center justify-between&quot;]/div[@class=&quot;hidden md:block&quot;]/div[@class=&quot;ml- flex items-center md:ml-6&quot;]/div[@class=&quot;ml-10 flex items-baseline space-x-4&quot;]/a[@class=&quot;text-gray-700 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium&quot;]</value>
      <webElementGuid>222f0d5e-3025-4629-a971-5e06c27db8c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Configuration')]</value>
      <webElementGuid>27038707-0155-461c-98cf-6967acb3c534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options'])[1]/preceding::a[1]</value>
      <webElementGuid>2689077f-eef0-4ae2-86fc-c13dee2cf808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menus'])[1]/preceding::a[2]</value>
      <webElementGuid>e2313dd3-d36a-4918-ac4f-543d770898bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Configuration']/parent::*</value>
      <webElementGuid>45f014ae-e45b-47c7-acff-3d5f2491ff05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'page/configurations/')]</value>
      <webElementGuid>e6f978c1-d36c-4a8d-a92a-15bf245fbbdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>c6434c70-918b-46c0-80ac-3842a033a644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'page/configurations/' and (text() = 'Configuration' or . = 'Configuration')]</value>
      <webElementGuid>df952670-f38d-45a9-9be7-0dd3b8225be0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
