<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Configuration_h-a w-14</name>
   <tag></tag>
   <elementGuidId>f386c21c-bfc3-4ef5-a2c5-3eff697c7bd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.h-a.w-14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Cap Builder Admin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a758fdbc-5db5-4632-b386-5cba33048581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Cap Builder Admin</value>
      <webElementGuid>ea35a945-1b61-4832-b03b-242a92b0cafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>258dcb65-1be2-4936-a25e-09c1178e9a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>3b738fd8-2945-4031-8e19-fe77a7353544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>6e3d097b-b54a-4e08-9f7a-f3b24f5041af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>2e9f2362-cfaa-4d6c-8d45-879b9715cd9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>28ebe517-1872-4907-8156-917dbb8361ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-a w-14</value>
      <webElementGuid>46664211-442d-44e7-b714-4c1184c791b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2Fneweralogo.webp&amp;w=32&amp;q=75 1x, /_next/image?url=%2Fneweralogo.webp&amp;w=64&amp;q=75 2x</value>
      <webElementGuid>d68162a8-b31e-4045-86b4-3d652e19035f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2Fneweralogo.webp&amp;w=64&amp;q=75</value>
      <webElementGuid>acc476a3-b43f-472d-9746-adfc91472417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;h-full bg-gray-100&quot;]/body[@class=&quot;__className_0ec1f4 bg-white mx-auto h-full&quot;]/header[1]/nav[@class=&quot;bg-white border-2 border-white border-b-gray-100&quot;]/div[@class=&quot;mx-auto- -max-w-7xl px-4 sm:px-6 lg:px-8&quot;]/div[@class=&quot;flex h-16 items-center justify-between&quot;]/div[@class=&quot;flex items-center&quot;]/div[@class=&quot;flex-shrink-0&quot;]/img[@class=&quot;h-a w-14&quot;]</value>
      <webElementGuid>6a020950-d690-46fc-a460-b6e0a6f46a0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Cap Builder Admin']</value>
      <webElementGuid>b431bf6c-bed6-4836-b045-2dce71a67d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>2cf62434-a5bb-44b3-89ba-55bb3056673d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Cap Builder Admin' and @src = '/_next/image?url=%2Fneweralogo.webp&amp;w=64&amp;q=75']</value>
      <webElementGuid>9efea5a4-2f51-4c2f-8e15-669428cb3bd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
