<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Options</name>
   <tag></tag>
   <elementGuidId>f506d452-123a-4dbb-b2fa-96cebc3988ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Options')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f0b24457-1d9d-4056-8d47-19141d34750f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-gray-700 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium</value>
      <webElementGuid>326a14dc-05d9-4c60-9815-501e380f4d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>page/options/</value>
      <webElementGuid>5a0188eb-2ddb-45f0-9f38-7217c7df58dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Options</value>
      <webElementGuid>964e6690-bd27-4f59-a399-9c8add8f1c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;h-full bg-gray-100&quot;]/body[@class=&quot;__className_0ec1f4 bg-white mx-auto h-full&quot;]/header[1]/nav[@class=&quot;bg-white border-2 border-white border-b-gray-100&quot;]/div[@class=&quot;mx-auto- -max-w-7xl px-4 sm:px-6 lg:px-8&quot;]/div[@class=&quot;flex h-16 items-center justify-between&quot;]/div[@class=&quot;hidden md:block&quot;]/div[@class=&quot;ml- flex items-center md:ml-6&quot;]/div[@class=&quot;ml-10 flex items-baseline space-x-4&quot;]/a[@class=&quot;text-gray-700 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium&quot;]</value>
      <webElementGuid>3858860d-3808-4b38-8bf8-0db393ba1ac9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Options')]</value>
      <webElementGuid>9c79c22f-f0f1-4c9f-807b-f7b883b07c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configuration'])[1]/following::a[1]</value>
      <webElementGuid>dc28a56c-2517-4885-b37d-95a46d7f3906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menus'])[1]/preceding::a[1]</value>
      <webElementGuid>9b6798f0-1359-4962-8195-5dcf8ccc2d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logos'])[1]/preceding::a[2]</value>
      <webElementGuid>d8f3471d-4eed-4d60-8f63-3d737bd0d230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Options']/parent::*</value>
      <webElementGuid>8ae6bee5-fa6e-49d7-a4fd-242f7621db13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'page/options/')]</value>
      <webElementGuid>9e7f7d7b-2b9f-4ece-8888-a04e044e19c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>0f2bc235-02b2-4961-9dd7-2ab0ed2e1cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'page/options/' and (text() = 'Options' or . = 'Options')]</value>
      <webElementGuid>e9655f80-0f74-4db6-8a3d-ee6b36ec2bb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
