<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Color</name>
   <tag></tag>
   <elementGuidId>9b763373-6bfd-4cd1-9c0e-1738564bbb9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Display Name'])[1]/following::th[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>48fbd807-28d8-4561-b4e1-faace581f5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>56687ae0-8a2e-4349-b51f-3e4a7828c70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flext flex-row flex-nowrap gap-1 px-3 py-3 font-medium text-gray-900 whitespace-nowrap</value>
      <webElementGuid>251890aa-0a70-41df-b7d9-95129d38f477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Color</value>
      <webElementGuid>2aa024af-4b76-4f96-8b8e-59dd8c951368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;h-full bg-gray-100&quot;]/body[@class=&quot;__className_0ec1f4 bg-white mx-auto h-full&quot;]/main[@class=&quot;md:flex max-h-fit h-full overflow-hidden&quot;]/div[@class=&quot;max-h-screen overflow-hidden overflow-y-scroll- flex-1&quot;]/div[@class=&quot;min-h-full&quot;]/main[1]/div[@class=&quot;#page-container- #relative- #isolate- rounded-lg border border-gray-200 shadow-md #m-5 #md:pb-5  bg-white max-h-screen-&quot;]/div[@class=&quot;max-h-[600px] sm:max-h-[72vh] md:max-h-[72vh] h-full overflow-y-auto rounded-md border shadow-sm m-5 md:pb-5 border-collapse bg-white text-left text-sm text-gray-500&quot;]/table[@class=&quot;min-w-full divide-y divide-gray-200&quot;]/thead[@class=&quot;sticky top-0 bg-gray-50&quot;]/tr[1]/th[@class=&quot;flext flex-row flex-nowrap gap-1 px-3 py-3 font-medium text-gray-900 whitespace-nowrap&quot;]</value>
      <webElementGuid>a837d015-7a7d-4131-9258-c836ed9f72c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Display Name'])[1]/following::th[1]</value>
      <webElementGuid>39fcc205-306a-4d98-83e8-e4804b83d3f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::th[2]</value>
      <webElementGuid>adc0adef-c963-495d-b31b-cafdec810ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Texture'])[1]/preceding::th[1]</value>
      <webElementGuid>817b8639-9a71-4ed4-9a93-1a12e3453179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAP Material'])[1]/preceding::th[2]</value>
      <webElementGuid>1787d009-0458-4c2a-ae6f-9b01c6524e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Color']/parent::*</value>
      <webElementGuid>b75e6519-d1e8-4585-9e85-d7632f6c2af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]</value>
      <webElementGuid>8205ab48-0f1b-45c0-84b5-6e31d75df917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Color' or . = 'Color')]</value>
      <webElementGuid>f10d62a7-5698-4c70-9944-932f9e74f18d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
